image: fedora:30

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

build:
  stage: build
  retry: 2
  cache:
    paths:
      - ./
    key: "$CI_COMMIT_REF_SLUG"
  script:
    - dnf install -y @development-tools gcc-c++ gcc-gnat zlib-devel perl-Digest-MD5 perl-Digest-SHA uuid-devel pcsc-tools ncurses-devel lbzip2 libuuid-devel lzma elfutils-libelf-devel bc bzip2 bison flex git gnupg iasl m4 nasm patch python wget libusb-devel cmake automake pv bsdiff autoconf libtool expat-devel boost-devel libaio-devel cpio texinfo diceware
    - git fetch origin 
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - make BOARD=x230-hotp_verification || (find ./build/log/ -cmin 1|xargs tail; exit 1)
    - echo "x230-hotp_verification hashes:"
    - cat ./build/x230-hotp_verification/hashes.txt
  artifacts:
    paths:
      - ./build/x230-hotp_verification/coreboot.rom
      - ./build/x230-hotp_verification/x230-hotp_verification-top.rom
      - ./build/x230-hotp_verification/x230-hotp_verification-bottom.rom
      - ./build/x230-hotp_verification/hashes.txt
      - ./build/x230-hotp_verification/initrd.cpio.xz
